### ISSUE TITLE
actions运行报错了

### ISSUE THREAD

**Issue by hietsusama** [CokeMine/EUserv_extend#1]
Run python main.py
Traceback (most recent call last):
******************************
正在续费第 1 个账号
  File "/home/runner/work/EUserv_extend/EUserv_extend/main.py", line 127, in <module>
    SERVERS = get_servers(sessid, s)
  File "/home/runner/work/EUserv_extend/EUserv_extend/main.py", line 54, in get_servers
    flag = True if tr.select('.kc2_order_action_container .kc2_order_extend_contract_term_container')[
IndexError: list index out of range
Error: Process completed with exit code 1.

但是邮件显示延长成功。

目前账号里面有两个免费小鸡，请问是都可以延长还是说只能延长账户中的一个？

**Comment by 1ceshi** [comment]
具体是怎么操作呀，有图文教程吗，新手小白初入githuub。

**Comment by CokeMine** [comment]
有点奇怪，我尝试改了改。

默认是获取账户中所有的小鸡并延期

**Comment by hietsusama** [comment]
> 有点奇怪，我尝试改了改。
> 
> 默认是获取账户中所有的小鸡并延期

续期是成功了 但是显示失败很尴尬。另外我加了一个手动run按钮 大佬合并一下呗

**Comment by hietsusama** [comment]
> 有点奇怪，我尝试改了改。
> 
> 默认是获取账户中所有的小鸡并延期

我pull了新的现在正常了。感谢大佬，我最近改改试试放到scf上，放个图文教程到时候推上来 谢谢啦
