### ISSUE TITLE
The number of usernames and passwords do not match! 问题

### ISSUE THREAD

**Issue by nnhym** [CokeMine/EUserv_extend#15]
首先感谢作者提供的脚本。
查看了作者的代码。
`
user_list = USERNAME.split(',')
    passwd_list = PASSWORD.split(',')
    if len(user_list) != len(passwd_list):
        print("The number of usernames and passwords do not match!")
        exit(1)
`
现在报一个问题，如果环境变量中USERNAME或者PASSWORD中有“,”就会提示“The number of usernames and passwords do not match!”，其中密码中是最容易包含“,”的。建议作者采用其他的分割符。比如：两个空格或者中文标点。

**Comment by CokeMine** [comment]
这个问题我在README里写了，会考虑修改
