### ISSUE TITLE
Euserv需要一段时间确认个人信息，否则无法续期

### ISSUE THREAD

**Issue by CokeMine** [CokeMine/EUserv_extend#23]
Euserv需要一段时间确认个人信息，否则无法续期，也无法使用管理小鸡的正常功能。
初步判断为每月1号？

**Comment by MasterOfStar** [comment]
可能是一号凌晨(GMT)的一小段时间？脚本在默认的0:50（GMT）运行出现问题，但现在（12:52 GMT--北京时间20:52）运行是正常的。

**Comment by CokeMine** [comment]
> 可能是一号凌晨(GMT)的一小段时间？脚本在默认的0:50（GMT）运行出现问题，但现在（12:52 GMT--北京时间20:52）运行是正常的。

这...对，也有这种可能性，我就觉得就算确认个人信息，也不应该是每个人都是一天来着

**Comment by if1y** [comment]
看起来是的。同样从昨天开始出现actions失败，刚才登陆发现要确认。

**Comment by CokeMine** [comment]
> 看起来是的。同样从昨天开始出现actions失败，刚才登陆发现要确认。
我手贱自己确认了下，等下次让我确认的时候我再做一下判断，然后更新下脚本

**Comment by if1y** [comment]
今天登陆发现又要确认信息，目前看是3个月一次？

**Comment by CokeMine** [comment]
> 今天登陆发现又要确认信息，目前看是3个月一次？

确实是需要定期确认信息，但是不确认的话对续费不造成影响

**Comment by if1y** [comment]
> > 今天登陆发现又要确认信息，目前看是3个月一次？
> 
> 确实是需要定期确认信息，但是不确认的话对续费不造成影响

也对，你一说我想起来了，之前失败是因为网站崩，那没事了~
