### ISSUE TITLE
针对脚本执行频率的建议

### ISSUE THREAD

**Issue by if1y** [CokeMine/EUserv_extend#26]
从近期的情况来看，官方可能已经注意到并开始整治机器人的情况了（https://github.com/CokeMine/EUserv_extend/issues/23 需要确认联系信息）。

另外大量的自动化请求也应该给平台带来了压力（https://github.com/CokeMine/EUserv_extend/issues/25）。

因此，也是为了珍惜和感谢平台提供的资源，实现“可持续发展”，建议对任务执行规则进行调整：
由于续期只需要一个月一次，且有10天的缓冲期。所以可以把执行频率改成2-3天一次，甚至**直接设置成自己机器对应的那一周里执行几次即可**。
而不是像现在，每天都执行。这样对 Actions 资源也是一种浪费。

**Comment by CokeMine** [comment]
默认执行时间已经改成了每周日、周三执行。但是我没法改已经Fork的700多个人（
修改执行时间也得是让使用用户自己去更新。。就看他们愿不愿意了。。

**Comment by if1y** [comment]
嗯，也希望看到本 issue 的朋友能都能适当修改吧！

~~“羊毛”不能薅死了~~ 😂

**Comment by Jacobax** [comment]
一开始就改为每周一次了

**Comment by CokeMine** [comment]
没人听我的，我已经把默认的Action删了

**Comment by if1y** [comment]
理解。
如果是有Actions方面的担忧，建议同时清除历史commits～
