### ISSUE TITLE
sre24推送不起作用

### ISSUE THREAD

**Issue by ghost** [cokemine/EUserv_extend#43]
添加机密 TOKEN 及代码 但是执行代码后无推送

**Comment by tonytony2020** [comment]
推送跟其他一些乱七八糟的推送不一样不是无脑推，只会在成功或者失败，关键信息才推送。

手动执行提示啥？

**Comment by p2plover** [comment]
我不知道起不起作用，因为我的续期也不起作用。
******************************
正在续费第 1 个账号
检测到第 1 个账号有 1 台VPS，正在尝试续期
ServerID: 326216 does not need to be renewed
Checking.......
ALL Work Done! Enjoy
******************************
确实需要在2月7日前续期的，但它却没有续期。脚本运行完后，去网站一看，真的没有续期。

**Comment by tonytony2020** [comment]
推送应该没啥问题。如下图所示，进入逻辑A部分才会触发通知，从你反馈是进入B部分。
![11](https://user-images.githubusercontent.com/63030915/106692755-08ea1300-6610-11eb-92e5-2a00002b9b19.png)

对续期逻辑有疑问可以at下作者 @CokeMine 。

**Comment by p2plover** [comment]
起作用，今早收到推送，账户登录失败。。。手动运行都可以登录的，自动的就不行了？

**Comment by tonytony2020** [comment]
登陆问题请咨询 @cokemine
