### ISSUE TITLE
没必要fork本仓库

### ISSUE THREAD

**Issue by imba-tjd** [CokeMine/EUserv_extend#45]
这样不方便更新
完全可以在CI里git clone下来运行，或者添加一个setup.py用pip安装
如果怕新手不会，可以创建另一个repo供其他人fork

关于自动暂停，根据 https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow 它只说了public的repo会60天不用就暂停，我没试过private的会怎么样？

**Comment by CokeMine** [comment]
好像确实是这样，只要另建一个仓库Checkout这个仓库的代码就可以了。。。。不过已经1k多人fork了。。懒得去做了（
只有Fork的public仓库会这样，非Fork的Public也不会自动暂停。调整成private应该不会自动暂停。
但是private仓库用Github的原生CI是有限制时常的。好像是2000小时/月？（指非Pro账号）
