### ISSUE TITLE
请问运行报错这个怎么办

### ISSUE THREAD

**Issue by 12123ads** [CokeMine/EUserv_extend#57]
Error: Process completed with exit code 1.

**Comment by CokeMine** [comment]
> 若部署在云函数平台上导致的任何出错，不接受反馈。

**Comment by 12123ads** [comment]
GitHub Actions也是吗

**Comment by CokeMine** [comment]
> GitHub Actions也是吗

#25 #26

**Comment by 12123ads** [comment]
登录过了，没验证，刚刚又运行了一遍，还是这样。。。

**Comment by huiyio** [comment]
?加我QQ:2818442945


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CokeMine/EUserv_extend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月20日(星期六) 晚上6:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CokeMine/EUserv_extend] 请问运行报错这个怎么办 (#57)





 
Reopened #57.

**Comment by CokeMine** [comment]
@12123ads 我在本地运行没有出错，最大的可能是EUserv封了GitHub Workflows的IP

**Comment by 12123ads** [comment]
谢谢大佬，运行不报错了
