### ISSUE TITLE
脚本是不是失效了?

### ISSUE THREAD

**Issue by liuckv** [cokemine/EUserv_extend#59]
[](url)
![QQ图片20210323155112](https://user-images.githubusercontent.com/70507697/112112036-f6dc2800-8bef-11eb-9481-b5a576e9118c.png)

**Comment by CokeMine** [comment]
设置帐号密码

**Comment by liuckv** [comment]
![微信图片_20210324112209](https://user-images.githubusercontent.com/70507697/112249837-6b1bd780-8c93-11eb-81d7-ecf0898abed3.png)
红箭头所指的地方吧？

**Comment by CokeMine** [comment]
本地运行直接把这里改成字符串就行了

**Comment by liuckv** [comment]
我直接填上本人的账号和密码运行，就提示第一个图片的错误。
另外，这个怎么提交到百度云函数里面运行？

**Comment by cncherisher** [comment]
把os.environ["USERNAME"]整个换成你的账号
把os.environ["PASSWORD"]整个换成你的密码

**Comment by zaxbpc0** [comment]
注意格式：
USERNAME = 'mymail@mail.com'
PASSWORD = '1234567890'
