### ISSUE TITLE
vps运行出错，这是什么原因

### ISSUE THREAD

**Issue by KuYeHQ** [CokeMine/EUserv_extend#61]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    USERNAME = os.environ["XXXX@gmail.com"]
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'XXXX@gmail.com'

大佬看下

**Comment by CokeMine** [comment]
把取环境变量的7、8行，https://github.com/CokeMine/EUserv_extend/blob/444cd4d37a28137547a1c4ef51db89442f4171b6/main.py#L7-L8
用`vim`编辑换成自己的账号密码

**Comment by KuYeHQ** [comment]
USERNAME = os.environ["kuyehq@gmail.com"]
PASSWORD = os.environ["QXXXXX"]
TOKEN = os.environ.get("TOKEN", "")
是这样配置的啊，大佬
环境也搭了

**Comment by CokeMine** [comment]
去掉os.environ什么的。换成字符串常量

**Comment by KuYeHQ** [comment]
----------------------------------------------------------------------------
******************************
正在续费第 1 个账号
检测到第 1 个账号有 1 台VPS，正在尝试续期
ServerID: 342132 does not need to be renewed
Checking.......
ALL Work Done! Enjoy
******************************
成功了，谢谢大佬
