### ISSUE TITLE
报错，找不到pip

### ISSUE THREAD

**Issue by sunnynctu** [CokeMine/EUserv_extend#62]
`root@instance-xxx:~# apt install python3 python3-pip -y

Reading package lists... Done

Building dependency tree
       
Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).

python3-pip is already the newest version (20.0.2-5ubuntu1.1).

0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.

root@instance-xxx:~# pip install requests beautifulsoup4

-bash: pip: command not found`

**Comment by CokeMine** [comment]
试试`pip3`

**Comment by sunnynctu** [comment]
> 试试`pip3`
感谢大佬及时解答，已经成功了
`root@instance-xxx:~# python3 main.py
******************************
正在续费第 1 个账号
检测到第 1 个账号有 1 台VPS，正在尝试续期
ServerID: 3****4 does not need to be renewed
Checking.......
ALL Work Done! Enjoy
******************************
正在续费第 2 个账号
检测到第 2 个账号有 1 台VPS，正在尝试续期
ServerID: 3****7 does not need to be renewed
Checking.......
ALL Work Done! Enjoy
******************************`
