### ISSUE TITLE
续期失败

### ISSUE THREAD

**Issue by Stonewalling** [cokemine/EUserv_extend#66]
发现原因,是网站的续期操作发生了变化

**Comment by hjh142857** [comment]
似乎是登录出现了问题，直接登录不上了

**Comment by huaxinCLUB** [comment]
通过debug发现是login函数不能正确登陆return -1造成的登陆失败



正在续费第 1 个账号
第 1 个账号登陆失败，请检查登录信息
******************************

**Comment by cokemine** [comment]
有没有大佬修复了推个PR来🥺

**Comment by ZhangTianrong** [comment]
不懂啊，request 和浏览器完全一致，response 是 200 但是内容为空。

**Comment by apkipa** [comment]
> 不懂啊，request 和浏览器完全一致，response 是 200 但是内容为空。应该还是 sess_id 的问题，我用浏览器先访问登陆界面获取 sess_id 后用脚本登录是没问题的，但是我尝试先 session.get 获取 sess_id 怎么就不对了呢？

因为服务器会通过检测这个 sess_id 是否访问了 https://support.euserv.com/pic/logo_small.png 来判断是否是脚本登陆，而且坑应该不止这些。

**Comment by huaxinCLUB** [comment]
特别感谢[apkipa](https://github.com/apkipa)大佬在[issues](https://github.com/cokemine/EUserv_extend/issues/66#issuecomment-877730466)中提供的思路，已提交pr等待作者审核，着急的可以去[我的仓库](https://github.com/huaxinCLUB/EUserv_extend)查看哟

**Comment by cokemine** [comment]
现在登录是可以了，但是不确定是不是能续期（

**Comment by huaxinCLUB** [comment]
> 现在登录是可以了，但是不确定是不是能续期（
我pr前测试的是可以成功获取到账号下的vps的，只不过我的还没到续费的时候，所以提示不需要续费。有人可以试一下吗

**Comment by dawnli-github** [comment]
还是不能登录，PROXIES需要改吗，改了和没改都是登录失败嘞

**Comment by doublog** [comment]
******************************
正在续费第 1 个账号
第 1 个账号登陆失败，请检查登录信息
******************************
----------------------------------------------------------------------------
★[2021-07-11 17:04:06] Successful
----------------------------------------------------------------------------

还是登陆失败呢。。不知道怎么回事。。

**Comment by DaoChen6** [comment]
我的已经可以正常续期了

**Comment by DaoChen6** [comment]
@huaxinCLUB 大佬，啥时候多加几个推送，这个sre24不能推送到TG啊

**Comment by doublog** [comment]
> 我的已经可以正常续期了

哦？你用的这个脚本可以正常用？

**Comment by DaoChen6** [comment]
> > 我的已经可以正常续期了
> 
> 哦？你用的这个脚本可以正常用？

对，我用EUserv的机子可以正常使用

**Comment by doublog** [comment]
> > > 我的已经可以正常续期了
> > 
> > 
> > 哦？你用的这个脚本可以正常用？
> 
> 对，我用EUserv的机子可以正常使用

哦？你是在euserv机器上执行的这个脚本吗？
那我也去试试用这台机器执行下。谢谢

**Comment by lem0nb** [comment]
大佬，好像不能用
******************************
正在续费第 1 个账号
第 1 个账号登陆失败，请检查登录信息
******************************

**Comment by Stonewalling** [comment]
> 大佬，好像不能用
> 
> 正在续费第 1 个账号
> 第 1 个账号登陆失败，请检查登录信息

可以用的，我自己的腾讯服务器上已经能正常续费了，腾讯的函数云我也失败了
