### ISSUE TITLE
sre24推送报错

### ISSUE THREAD

**Issue by DaoChen6** [cokemine/EUserv_extend#74]
![image](https://user-images.githubusercontent.com/63903027/125919746-9aa0ae3a-076c-4f3d-81a0-e8d1938e53eb.png)

**Comment by cokemine** [comment]
我的锅，我从来没用过这些推送根本不知道他接口返回了啥（
应该是这样
fixed in https://github.com/cokemine/EUserv_extend/commit/b8b8c02dec0e0f55e20adf380ef6c506e088c9f2

**Comment by DaoChen6** [comment]
ok我试试

**Comment by DaoChen6** [comment]
还是不行，
![image](https://user-images.githubusercontent.com/63903027/125920859-2dd570f8-8aef-4515-ad56-c54fa5139fec.png)

**Comment by cokemine** [comment]
嗯...这样应该行了

**Comment by DaoChen6** [comment]
#75 嗯…那个失败和成功反了

**Comment by cokemine** [comment]
为什么200状态码会表示失败的状态？

**Comment by DaoChen6** [comment]
诶，我运行了它提示失败，但推送成功

**Comment by DaoChen6** [comment]
要不再看看？它返回的好像不是200

**Comment by DaoChen6** [comment]
诶，好像没错啊，状态码是200的话提示成功，不是的话失败

**Comment by cokemine** [comment]
我改回了官方文档的写法，他这样写的原因可能是成功的`code`不一定是200，有可能是201、202、20x

**Comment by DaoChen6** [comment]
OK
