### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hackmln** [cokemine/EUserv_extend#81]
## 开始执行... 2021-08-11 08:27:57

Traceback (most recent call last):
  File "/ql/scripts/XUFEI.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

## 执行结束... 2021-08-11 08:27:58  耗时 1 秒

**Comment by DaoChen6** [comment]
请安装好beautifulsoup4
```pip install requests beautifulsoup4```
